[versions]
accompanist = "0.37.3"
activityCompose = "1.12.3"
agp = "9.0.0"
appcompat = "1.7.1"
camerax = "1.5.3"
composeBom = "2026.01.01"
connectClient = "1.1.0"
coreKtx = "1.17.0"
espressoCore = "3.7.0"
firebaseBom = "34.9.0"
firebaseUiAuth = "9.1.1"
googleServices = "4.4.4"
hilt = "2.59.1"
hiltAndroidCompilerVersion = "2.59.1"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.3.10"
kotlinxSerializationJson = "1.10.0"
ksp = "2.3.4"
lifecycleRuntimeKtx = "2.10.0"
lifecycleViewmodelCompose = "2.10.0"
mockk = "1.14.9"
navigationCompose = "2.9.7"
textRecognition = "16.0.1"
ycharts = "2.1.0"


[libraries]
accompanist-permissions              = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
androidx-activity-compose            = { group  = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-appcompat                   = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-camera-camera2              = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
androidx-camera-compose              = { module = "androidx.camera:camera-compose", version.ref = "camerax" }
androidx-camera-core                 = { module = "androidx.camera:camera-core", version.ref = "camerax" }
androidx-camera-lifecycle            = { group  = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
androidx-camera-mlkit-vision         = { module = "androidx.camera:camera-mlkit-vision", version.ref = "camerax" }
androidx-compose-bom                 = { group  = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-connect-client              = { module = "androidx.health.connect:connect-client", version.ref = "connectClient" }
androidx-core-ktx                    = { group  = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core               = { group  = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit                       = { group  = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx       = { group  = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-material3                   = { group  = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose          = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-ui                          = { group  = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics                 = { group  = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-test-junit4              = { group  = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-manifest            = { group  = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-tooling                  = { group  = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview          = { group  = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material-icons               = { group  = "androidx.compose.material", name = "material-icons-core" }
firebase-analytics                   = { module = "com.google.firebase:firebase-analytics" }
firebase-auth                        = { module = "com.google.firebase:firebase-auth" }
firebase-bom                         = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firestore                   = { module = "com.google.firebase:firebase-firestore" }
firebase-ui-auth                     = { module = "com.firebaseui:firebase-ui-auth", version.ref = "firebaseUiAuth" }
hilt-android                         = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler                = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompilerVersion" }
junit                                = { group  = "junit", name = "junit", version.ref = "junit" }
kotlinx-serialization-json           = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
mockk                                = { module = "io.mockk:mockk", version.ref = "mockk" }
text-recognition                     = { module = "com.google.mlkit:text-recognition", version.ref = "textRecognition" }
ycharts                              = { module = "co.yml:ycharts", version.ref = "ycharts" }

[plugins]
android-application  = { id = "com.android.application", version.ref = "agp" }
google-services      = { id = "com.google.gms.google-services", version.ref = "googleServices" }
hilt                 = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android       = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose       = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-ksp           = { id = "com.google.devtools.ksp", version.ref = "ksp" }


